export type SwapData = { amountOut: string, priceImpact: number };
export type AddLiquidityData = { amountLpOut: string; amountYtOut: string; priceImpact: number };
export type AddLiquidityDualData = { amountOut: string, priceImpact: number };
export type RemoveLiquidityData = { amountOut: string, priceImpact: number };
export type RemoveLiquidityDualData = { amountTokenOut: string; amountPtOut: string, priceImpact: number };
export type MintPyData = { amountOut: string, priceImpact: number };
export type RedeemPyData = { amountOut: string, priceImpact: number };
export type TransferLiquidityData = { amountLpOut: string; amountYtOut: string, priceImpact: number };
export type RollOverPtData = { amountPtOut: string, priceImpact: number };